server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: vs0000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true